AgonPlatform/agon-vdp

- video/agon_audio.h
- video/agon_keyboard.h
- video/agon_screen.h
- video/cursor.h
- video/envelopes/frequency.h
- video/envelopes/volume.h
- video/graphics.h
- video/sprites.h
- video/types.h
- video/vdp_protocol.h
- video/vdu.h
- video/vdu_audio.h
- video/vdu_sprites.h
- video/vdu_sys.h
- video/video.ino
- video/viewport.h
Change to use proper C++ data types, rather than Arduino aliases.
As part of this the use of data types has been rationalised, making use of the C++ `auto` operator, and picking more appropriate sizes of data elements.  This 
A custom C++ allocator has been added to help facilitate the use of PSRAM.  This was taken from [Dave Plummer's](https://www.youtube.com/@DavesGarage) [NightDriverStrip project](https://github.com/PlummersSoftwareLLC/NightDriverStrip).
Audio code has also been changed to make better use of PSRAM, and to use some slightly more efficient allocation techniques, such as swapping some uses of `std::array` to `std::unordered_map`
> Improved data types and memory usage

- video/agon.h
- video/video.ino
fixes an issue for the emulator where the cursor rapidly flashed as it runs on hardware faster than an ESP32
> change cursor drawing to be time based

- video/vdu_stream_processor.h
- video/video.ino
fixes an issue whereby if the z80 kept the VDP busy then keyboard input wouldn’t be picked up.
this meant that a BASIC program that had a loop continually drawing to the screen couldnt be escaped from
> fix keyboard when busy

- video/agon_audio.h
- video/agon_screen.h
- video/audio_channel.h
- video/envelopes/frequency.h
- video/envelopes/volume.h
- video/graphics.h
- video/sprites.h
- video/vdu.h
- video/vdu_audio.h
- video/vdu_stream_processor.h
- video/vdu_sys.h
- video/viewport.h
fixes all compiler warnings by either removing unnecessary checks, fixing types to be more appropriate, and fixing a few minor bugs that these warnings were telling us about
one warning remains, which is to do with the RTC day of year value in our RTC VDP info packet.  this warning reflects a bug as we’re trying to send a day of year (range 0-365) in a single byte (range 0-255) which doesn’t fit.
> fix compiler warnings

- video/graphics.h
- video/vdu.h
- video/vdu_sprites.h
This PR extends plot support to include significantly more of Acorn's PLOT system, including features added by the Graphics eXtension ROM.
All plot commands now support all of the different variants _except_ for the "logical inverse colour" modes.  This means both relative and absolute versions as well as "foreground" vs "background" colour choice.
Bugs in circle command related to how it calculated radius have been fixed.  Filled circle operation added.
Line commands that omit first and/or last pixels are supported.
Filled rectangle and parallelogram operators have been added, and also copy/move screen area is also supported.
> Extended Plot support

- video/agon.h
- video/vdu_audio.h
- video/vdu_buffered.h
- video/vdu_sprites.h
- video/vdu_stream_processor.h
- video/vdu_sys.h
and remove _most_ blocking reads
- only remaining ones are inside `hexload.h`
`discardBytes` is also now non-blocking, so except for the use noted above this PR addresses #35
> implement readIntoBuffer

- video/agon.h
- video/agon_audio.h
- video/audio_channel.h
- video/audio_sample.h
- video/buffer_stream.h
- video/buffers.h
- video/enhanced_samples_generator.h
- video/hexload.h
- video/multi_buffer_stream.h
- video/sprites.h
- video/vdu_audio.h
- video/vdu_buffered.h
- video/vdu_sprites.h
- video/vdu_stream_processor.h
adds support for jump, conditional jump, copy, and consolidate, with placeholders for jump with offset calls
plus, bitmaps now use buffers!
oh, and samples too!!
bitmaps uploaded the "old-fashioned way" using `VDU 23, 27, 1` get stored in buffers numbered &FA00-&FAFF (64000-64255).  they therefore become editable using the buffered commands API.  all of the existing bitmap and sprite commands work as before - the nature of the API means that just two of them are restricted to using bitmaps in this range.
A few new bitmap commands have been added to allow for full 16-bit buffer IDs to be used for bitmaps, thus allowing many more bitmaps than was previously allowed.  to facilitate this the bitmaps/sprites API gains three new operators.  these correspond to the existing calls but have &20 …
> new buffered commands

- video/audio_channel.h
- video/audio_sample.h
- video/enhanced_samples_generator.h
- video/envelopes/volume.h
adds support for playing back an entire sample by sending zero as the duration to play note
NB if a volume envelope has been set on the channel then the duration will be the higher of the sample duration or the envelope release phase
> support zero duration sample playback

- video/version.h
- video/video.ino
move version info out to `version.h` file
version info now a semantic version, with major, minor, patch, and “candidate” info, as well as an indicator for candidate type (displayed if candidate number is non-zero)
support for showing an automatically-generated build number added, which can be provided by a build script and is intended to be derived from the git hash
with this approach it should also be possible in the future to add other tooling to automatically increment version numbers
version info also includes the codebase variant, allowing us to easily differentiate between Quark and Console8
> Semantic versioning

- platformio.ini
- video/video.ino
This adds platformio support without breaking the compatibility with arduino IDE.
> Add platformio.

- video/agon.h
- video/updater.h
- video/vdu_sys.h
shifts the updater command to sit under VDU 23,0,&A1.  commands under VDU 23,0 are intended to program the VDP hardware, so this is a better fit for these commands
improved handling of failure cases within the updater code.  failures to initiate the OTA system, or write OTA data should now discard serial data correctly and abort the update process
> some minor updater improvements

- video/hexload.h
The VDP hexload code now accepts the less frequently used type 02 record, using 20-bit segment addresses. I found that the objcopy tool, when not passing it a start-address parameter, emits these records at each 64KB boundary.
Reading the original Intel hex specification, it appears that tools <may> use these type of records, originally meant for cpu's with a 20bit address space. Latter tools mostly use 32-bit addresses.
Also now displaying errors to the user when the uploaded hex file partly overlaps with the ROM/flash area. Users tend to forget to -offset their hex codes, when converting a binary file without address meta-data, which then lands starting at address 0 (rom/flash area).
When omitting the first address record in a hex-file, the tool previously already set the start-address …
> Accepting segment records (type 02), warnings against overlapping ROM area addresses

- platformio.ini
This is just to make sure we are using the same version of espressif32 platform. Its the current release: https://github.com/platformio/platform-espressif32/releases
> Specify espressif32 to v6.4.0

- platformio.ini
It looks like platformio builds with 40MHz flash speed default. I verified this by the checksum of the generated bootloader.bin:
default 8649c816ab7ba68aa0ea4c98bb25ae3a  bootloader.bin
40mhz 8649c816ab7ba68aa0ea4c98bb25ae3a  bootloader.bin
80mhz 03b32c0cabcc0c857bc2ae029a696d68  bootloader.bin
> Specify board settings for cpu and flash speed.

- video/graphics.h
- video/vdu_sys.h
- video/viewport.h
VDU 24 sets the graphics viewport.  essentially it sets a clipping rectangle, and that should be all it does…
this fixes a bug whereby setting the graphics viewport would also effectively change the graphics origin.  this is contrary to how Acorn handles VDU 24.  (additionally setting the origin using VDU 29 would make for a double-offset)
all uses of `translateViewport` have been changed to use `translateCanvas` instead.  this should make behaviour more understandable, and more predictable, and consistent with Acorn.
besides fixing the observed VDU 24 issue, this PR changes the behaviour of two other commands so that they now both work strictly relative to the defined graphics origin, ignoring the defined graphics clipping rectangle/viewport.  those changes apply to `VDU 23,0,&89,4,x;t;` …
> fix VDU 24

- video/graphics.h
fab-gl’s canvas drawing routine for triangles when only using `fillPath` doesn’t _quite_ fill out the same pixels as plain line drawing.  this change ensures that filled triangles cover the same pixels as an equivalent line-drawn triangle
change also applied to parallelogram, since that draws in the same manner as triangles.
fixes breakintoprogram/agon-vdp#113
> fixes a triangle plot issue

- video/graphics.h
- video/vdu.h
Plot codes in the range of &E8-EF in Acorn’s GXR are for plotting the currently selected bitmap.  add support for that.
this allows bitmaps to be plotted using OS coordinates
> add support for bitmap PLOT code

- video/sprites.h
the bitmap plot code was always plotting based on the top-left corner of the bitmap.  when using OS coordinates this is incorrect behaviour - plot location should be based on the bottom-left corner, as per Acorn GXR
this fixes that behaviour
> fix bitmap plot screen location

- video/agon_ttxt.h
- video/graphics.h
- video/vdu.h
implements the line fill plot codes in blocks 0x48, 0x58, 0x68 and 0x78
NB this is a preliminary/experimental version, has not yet been fully tested, and is a slow/inefficient implementation
> add line-fill plot calls

- video/agon.h
- video/vdu_sys.h
- video/video.ino
terminal mode can be exited by sending a “user sequence” of characters, `ESC + ‘_#Q!$’` additionally an “emergency escape” key combo of ctrl+alt+f12 is supported
> add ability to exit terminal mode

- platformio.ini
- video/vdu_sprites.h
- video/vdu_stream_processor.h
- video/version.h
adds support for Acorn GXR style “copy screen to bitmap” command sequence
this is supported on both `VDU 23,27,1,n,0,0,0` to define bitmap `n` from the last two graphics cursor positions, using an 8-bit bitmap ID and also `VDU 23,27,&21,n;0;` using a 16-bit bitmap/buffer ID
these commands are compatible with the existing `VDU 23,27,1` and `VDU 23,27,&21` commands - the system can tell the difference as these variants require a zero “height” value
if the buffer specified already exists then it will be deleted/cleared before the new bitmap is created from the screen.  the resultant bitmap data will be in vdp-gl’s `Bitmap::Native` format
the original Acorn command documentation specifies that a few more zeros should be sent.  you can safely send additional zeros, as per Acorn’s …
> add support for copy-screen-to-bitmap

- video/vdu_sprites.h
- video/version.h
Somehow code to create bitmaps from an area of screen introduced a bug that would prevent mono bitmaps from working.  this fixes that issue
also bumps version number for new release with this fix
> Re-fix mono bitmap creation

- video/audio_sample.h
- video/enhanced_samples_generator.h
duration of a sample when played back calculation was buggy, resulting in looping samples when they shouldn’t
the sample generator’s `getDuration` call needs to calculate based on how long the _underlying_ audio system will take to step through samples, therefore it is the sample rate of the underlying system that needs to be used for calculations
> fix duration calculation

- video/agon.h
- video/vdu_stream_processor.h
- video/vdu_sys.h
reads colours, either from the palette, or one of the active colours
this is done using `VDU 23, 0, &94, colour`.  values will be returned using the `PACKET_SCRPIXEL` response packet, and therefore MOS will interpret these exactly the same as reading a screen pixel via `VDU 23, 0, &84`. values will therefore be exposed in MOS in the exact same `scrpixel` and `scrpixelIndex` sysvar bytes
when using this command, colours 0-63 will be interpreted as palette colours, 128 will return the currently selected text foreground colour, 129 the text  background colour, 130 graphics foreground, and 131 graphics background.  any other colour values will be ignored
> read colours

- video/graphics.h
- video/sprites.h
- video/vdu_buffered.h
- video/vdu_sprites.h
fixes issue with capturing bitmap to buffer zero
(the `createBuffer` call was preventing creation of buffer with ID 0, as it can’t be used as a place to redirect output)
fixes recently introduced bug with behaviour of VDU 23,27,3 caused by changes to drawBitmap which was compensating for the height of the bitmap when it should only do that for plot calls
> bitmap fixes

- video/buffers.h
VDUStreamProcessor::bufferReverse passes in a word when it calls this function, so valueSize should be 16 bits.  This will enable vertical flipping of bitmaps wider than 255 pixels.
> valueSize in reverseValues function changed from 8 bits to 16 bits

- video/agon.h
- video/agon_audio.h
- video/audio_channel.h
- video/audio_sample.h
- video/enhanced_samples_generator.h
- video/envelopes/adsr.h
- video/envelopes/frequency.h
- video/envelopes/multiphase_adsr.h
- video/envelopes/types.h
- video/vdu.h
- video/vdu_audio.h
- video/vdu_stream_processor.h
- video/vdu_sys.h
- video/video.ino
ensure all audio commands return a status value
only exceptions to this are comms timeouts, and even then some will result in a returned failure value
this fills in some gaps in the audio API with some calls that were not returning values.  if all calls return values then that makes it simpler to detect whether features are present and supported or not
Also allow samples being played to continue playing if volume is set/adjusted to zero.  They will continue to play (until completion) allowing their volume to be ramped back up.  Other mechanisms of aborting sample playback, such as changing to play a different sample, or setting duration to zero, will continue to work.  A channel playing a zero volume sample will allow "play note" to function to start a new note
Set volume command now …
> Further audio system enhancements

- video/graphics.h
fixes scrolling background colour issue - the new area of screen will now always be filled with the current text background colour
also adds support for movement directions 4-7, which move dependent upon the currently set cursor behaviour bits (see VDU 23,16)
adds support for movement amount of 0, to indicate move by 1 character in the given direction (as per Acorn’s implementation)
fixes #136, plus breakintoprogram/agon-vdp#58
> improve scroll region function

- video/graphics.h
- video/vdu.h
- video/vdu_stream_processor.h
- video/video.ino
VDU 2 and 3 are supported to enable and disable “printer”, which for our purposes on Agon is the debug serial terminal
VDU 1 will send next character to printer only
VDU 21 will disable the VDU command processor, allowing only output to “printer” - only VDU 1 and 6 commands will be processed
VDU 6 re-enables the command processor
VDU 20 (reset palette) added for good measure, as it was missing
various extra control keys are now supported on the VDP (ctrl B, C, F, G, L, N and O) and work as on Acorn systems (mirroring VDU 2, VDU 3, VDU 6 etc). ctrl-P is also supported, but toggles printer rather than performing a CLG, matching RTRussell’s BASIC
NB the processing of VDU 21 / VDU 6 currently differs from Acorn systems.  On an Acorn system, after performing a VDU 21, subsequent VDU commands …
> add support for VDU 2 and co

- video/agon.h
- video/vdu_buffered.h
- video/vdu_stream_processor.h
Building on #139 by @movievertigo 
Buffered copy ref command renumbered to 0x19 (as it may as well just be contiguously numbered with the current commands)
Most loops for buffered commands now use refs, which should prevent unnecessary copying of wrapper objects and structures, and in turn improve performance.
> Use references for more buffer command code

- video/agon.h
- video/vdu_buffered.h
- video/vdu_stream_processor.h
A version of the buffer copy command that just copies references to the blocks.  This speeds up situations where you're pulling in  data from various buffers to consolidate because the data only needs to be copied once.
> Buffer copy ref

- video/agon.h
- video/buffers.h
- video/vdu_buffered.h
- video/vdu_stream_processor.h
A new command that combines copy and consolidate into one.  The main advantage from a speed point of view is that it can reuse the buffer if it is the same size as the incoming data, so it doesn't need to remove and recreate it and can copy the source blocks directly in.
> Copy and consolidate

- video/vdu.h
range should have been 8-13, not 8-0x13 - doh!
> fix range of control codes sent to printer

- platformio.ini
- video/graphics.h
- video/sprites.h
- video/vdu.h
- video/vdu_sprites.h
supports all of Acorn's "basic" GCOL modes, 0-7 (0-4 from the Beeb, 5-7 from the Archimedes)
also support the "invert pixels" PLOT "mode", which operates the same as GCOL mode 4
> updates to support all GCOL and PLOT “modes”

- video/graphics.h
- video/vdu_sys.h
addresses #135 
Preliminary...  as this may have issues and needs some thought
This call won't work correctly with PLOT codes for lines that "omit first/last pixel", owing to how those PLOT operations are currently supported.  At this time it is not clear how to support those operations correctly
> simplistic support for setting line thickness

- platformio.ini
- video/vdp_protocol.h
- video/vdu.h
- video/vdu_buffered.h
- video/vdu_stream_processor.h
adds compiler optimisation flags (for platformio builds)
uses native timeout functionality of the Stream class for the eZ80 input stream.  our existing timeout functionality was actually redundant if we just configure the input stream correctly.  this greatly reduces the complexity of all stream read calls, providing a significant performance boost for all VDU command processing
> improve performance

- video/agon.h
- video/cursor.h
- video/graphics.h
- video/vdu.h
- video/vdu_sys.h
- video/video.ino
builds on #178 
adds support for all different cursor behaviours set via VDU 23,16,x,y
needs to be fully tested to compare to how RISC OS behaves
also includes preliminary support for `VDU 23,0,10,n` and `VDU 23,0,11,n` to set cursor display start/end row plus `VDU 23,0,&8A,n` and `VDU 23,0,&8B,n` to adjust cursor display start/end column (the latter wasn't part of what a Beeb could do).  this also includes the ability to set the flashing speed to fast (as opposed to the default slower flashing rate) and pick a "steady" (non-flashing) cursor.  `VDU 23,1,n` now supports options 2 and 3 for "steady" and "flashing" options instead of the previous off/on
> Enhanced cursor support

- video/viewport.h
fixes an issue whereby graphics viewports could only be defined with non-equal x or y values, which meant that viewports would be at least 2 pixels wide/tall
> allow single pixel height/width graphics viewports

- platformio.ini
- video/agon.h
- video/graphics.h
- video/vdu.h
- video/vdu_sys.h
enables all the dotted line PLOT codes
adds support for `VDU 23,6,n1,n2,n3,n4,n5,n6,n7.n8` to set the dotted line pattern
adds `VDU 23,0,242,n` (or `VDU 23,0,&F2,n`) to set the pattern length.  setting a length of zero will reset to default pattern, and length of 8
> update PLOT to support dotted lines

- video/graphics.h
- video/vdu.h
plot code 0x18 should be omitting the _last_ point from a line, rather than the first.  this bug was caused by Acorn’s GXR reference card incorrectly describing the PLOT code.  doh!
also ensure that vdu_plot is always in IRAM - which when running the triangle test gives us a boost of 7%
> fix plot code 0x18, and boost speed

- video/cursor.h
- video/graphics.h
- video/version.h
fixes for:
scroll directions when cursor had flipped its X and Y wasn’t looking for the correct “invert” behaviour, so would scroll in the wrong direction
when cursor was off the bottom of the screen an infinite loop could happen with the “cursor up” to bring the cursor back onto the screen if certain cursor behaviours were set
incorrect off-screen detection meant that for some combinations of cursor behaviour a scroll would get forced one row early
> even more cursor movement fixes

- video/agon.h
- video/context.h
- video/context/graphics.h
- video/context/viewport.h
- video/vdu.h
- video/vdu_sys.h
which will move the origin point to current graphics coordinates, and moves the currently set viewports by the same delta by which the origin has been moved.  shifted viewports are ensured to be on-screen.
setOrigin to graphics coordinates can now move origin to off-screen coordinates.  (it was previously restricting the new origin point to be on-screen, which isn’t necessary)
set origin commands now work correctly with relative plot commands
origin in context is now proper screen coordinates, including Y adjustment, instead of just a value scaled to match screen coordinates
bug fix:
VDU 26 the “reset viewports” command should have been resetting the graphics origin - it now does that
> add new “shift origin” command

- video/vdu_audio.h
- video/vdu_buffered.h
- video/vdu_stream_processor.h
when a buffered command call clears a buffer it should ensure that all users of that buffer (bitmaps, fonts, samples) should get cleared too
> ensure that buffers are properly cleared

- video/vdu.h
ensure that control characters are sent to “printer”
fixes an issue observed with the new optimised text printing system when "printer" is enabled
> fix printer output

- video/vdu.h
- video/vdu_stream_processor.h
- video/video.ino
add a `usePeek` argument to the `vdu` function, allowing the `print` function to disable peeking for more characters
this fixes issues observed with hexload
> ensure `print` doesn’t peek

- video/compression.h
- video/vdu_buffered.h
changes the `bufferDecompress` function, and the supporting `local_write_decompressed_byte` to work with a pre-allocated buffer of the complete original size of data, as derived from the compression header
also includes overrun protection for decompression
> decompresss into actual destination buffer

- platformio.ini
- video/hexload.h
General overhaul of most of the hexload code.
New features
- Adding an extended mode, wrapping Intel Hex transport inside a per-record CRC16 check
- In extended mode, retransmit at CRC16 failure
- CRC32 verification at end of transmission
- For now, any single-bit error from the ez80<->VDP side of things will trigger a record retransmit. We'll update this when the RTS/CTS is done in future
- Escape key escapes out of a started hexload
- Incoming high-speed overruns are detected, frames discarded
- 'Normal' Intel hex files pass as usual, without any CRC checks
Tested from Windows/Linux with the new sender script at my agon-hexload repo. The hexload client needs no change.
> Adding CRC16/32 verification to hexload

- video/vdu.h
Simple fix for #216.
Teletext mode must call set_window mode on the ttxt_instance in addition to the call to context->setTextViewport, not instead of.
> Fixed text viewport setting in MODE7

- video/agon.h
- video/types.h
- video/vdu_buffered.h
- video/vdu_stream_processor.h
allows for bitmapped data where a pixel is of 1-7 bits in length to be expanded into bytes, using a given map.  the map for expansion can either be provided with the command, or as a pointer to a buffer.  a pixel width optionally can be provided to indicate at what pixel width a byte alignment should occur, if required
addresses #218 via the "expand out data into RGBA2222 format" suggestion
> add “expand bitmap” buffer command

- platformio.ini
- video/agon.h
- video/agon_screen.h
- video/context.h
- video/context/graphics.h
- video/context/viewport.h
- video/test_flags.h
- video/types.h
- video/vdu_buffered.h
- video/vdu_stream_processor.h
- video/vdu_sys.h
adds support for creating (and adjusting) 2d affine transform matrixes in buffers.  affine transforms supported include rotate, scale (with separate x and y scaling values), skew, shear, and translation
a transform to be set to apply to all bitmap plot operations.  this works for all bitmap formats* in all screen depths
* the "native" bitmap format is not supported, but that format is not advised for use, as it works in a peculiar manner - in reality it is only used for sprites (restoring the background area), and for now sprites do not accept transforms
(for those interested, the crash on plotting bitmaps that had earlier been noted on this PR was caused by how the floating point unit and interrupts works.  the plotting actually worked in all screen modes except for single-buffered 64 …
> Transformed bitmap plots

- video/agon.h
- video/audio_channel.h
- video/context.h
- video/context/cursor.h
- video/context/graphics.h
- video/context/viewport.h
- video/vdu.h
improves readability of some enums, and ensures that they’re appropriately namespaced
> use enum class where appropriate

- video/context.h
- video/context/cursor.h
- video/context/graphics.h
- video/vdu.h
primary change is to track when plotting text, meaning that canvas calls to set up for text plotting can be omitted
with this setup, it typically scores under 001000 on badapplebenchmark - scores down to 000E70 have been observed
> optimised print routine

- .github/workflows/build.yml
A very simple addition, modelled after [the documentation](https://docs.platformio.org/en/latest/integration/ci/github-actions.html). Builds the firmware with PlatformIO on Windows, Linux and Mac to make sure it compiles fine on all platforms. Uses free Github CI runners.
For run logs see: https://github.com/maxgerhardt/agon-vdp/actions/runs/9587805332
Gives commits starting from the the nice green checkmark! :)
> Add PlatformIO CI

- video/multi_buffer_stream.h
ensure that calls to `read` and `peek` will return -1 if there is there isn’t a currently valid buffer block in MultiBufferStream
this fixes an issue where calling a buffer that ends with an incomplete VDU command would cause the VDP to fatally crash
Fixes #241
> fix MultiBufferStream read and peek

- video/context/graphics.h
when performing a copy/move rectangle plot, the underlying graphics system requires coordinates that stay within screen bounds, otherwise it will crash.  this change ensures that is the case
the way in which source/destination coordinates are handled has also been changed to ensure they will work correctly in the event that negative coordinates had been used
fixes #227
> ensure copy/move rectangle plot stays onscreen

- video/vdu.h
While using `set console 1` characters were dropped from output. This was caused by not doing `DBGSerial.write(next)` in `consoleMode`.
> Fixes dropped characters in console mode

- video/agon_screen.h
fixes an issue whereby the RGB2222 to palette lookup table wasn’t being updated when the palette was changed, which would mean that bitmaps would not be drawn using correct colours
Fixes #248
> fix: update palette LUT in paletted modes

- platformio.ini
- video/agon.h
- video/agon_audio.h
- video/agon_fonts.h
- video/audio_channel.h
- video/audio_sample.h
- video/buffer_stream.h
- video/buffers.h
- video/context/graphics.h
- video/multi_buffer_stream.h
- video/sprites.h
- video/types.h
- video/vdu_buffered.h
- video/vdu_context.h
- video/vdu_stream_processor.h
Adds in a few new matrix operation commands
Affine transform command gains a "translate by bitmap size" operation, which adds an x,y translate to the transform where the given x and y values are scaled by the given bitmap's width and height.  this is useful for adding in translate ops that are proportional to bitmap size, such as translating to negative half width and half height to centre the transform origin
New 3d affine transform command added.  this supports all of the same options as the 2d affine transform command, and will create a 4x4 affine transform matrix.  3d versions generally take 1 more argument, as they need arguments for a third dimension.  rotate for 3d takes 3 arguments (instead of 1) to rotate around all 3 axes
Generic "matrix manipulate" command added, which allows …
> More transform operations

- video/agon_screen.h
- video/context/graphics.h
- video/vdu.h
addresses an issue caused the the inclusion of new `updateRGB2PaletteLUT()` call when changing palette entries on paletted modes
the underlying issue was caused by the fact that the VDP was _not_ maintaining its own palette on these screen modes, and instead relying on the underlying LUT being essentially incorrect.  the LUT not being updated meant that an attempt to translate an incorrect RGB888 colour (as requested by the agon-vdp code) would translate to the _new_ signal colour (in the vdp-gl code)
this revision updates the agon-vdp side palette for all screen modes, thus meaning the updated LUT will operate correctly
this does introduce a new oddity related to duplicate palette entries, which the VDP previously didn’t appear to suffer from.  selecting “colour 14” when it has been …
> improved palette handling

- video/context/viewport.h
fixes an issue whereby cursor could be invisible after a viewport reset
fixes #254
> reset clipping rect on viewport reset

- video/audio_channel.h
fixes an issue observed when attempting to stop the note on a channel playing a sample that has a volume envelope set would cause the note to abruptly stop, rather than allowing the release phase of the envelope to happen
> fix for stopping samples with envelopes

- video/agon.h
- video/agon_ps2.h
- video/vdu_sys.h
- video/video.ino
`VDU 23,0,&99,virtualkey`
prompts a new keycode data packet to be sent to MOS with latest state of `virtualkey`
> add a check key command

- video/video.ino
This fixes an issue where two keyboard handlers are active in Terminal mode: the vdp-gl keyboard task, and the VDP's do_keyboard_terminal(). The effect of this duplication is that ~90% of keypresses are handled by vdp-gl, and ~10% by do_keyboard_terminal(). You can notice this in terminal-mode applications by the occasional dropping of keypresses in non-ascii keys (function keys, cursor keys). With this fix applied there are no dropped non-ascii keypresses.
> Remove custom terminal-mode keyboard handling

- platformio.ini
- video/agon_screen.h
ensures that `canvas->noOp()` is called before `canvas->waitCompletion(true)` when the “wait for vsync” command is processed.  when the drawing queue is empty `waitCompletion` always returns immediately, so this ensures that a no-op is present in the queue waiting to be processed.
fixes #271
> fix wait for vsync command

- video/agon_ps2.h
- video/context.h
- video/context/fonts.h
- video/context/graphics.h
- video/hexload.h
- video/types.h
- video/vdu_buffered.h
- video/vdu_sys.h
- video/video.ino
This effectively is a re-creation of #256 
(I undid that merge, as it made the git history too complex - hindsight says I should have performed a "squash and merge")
This PR will also include a fix for issue identified on #256 with matrix data not being correctly zero'd
> Unify emulator and main VDP codebases

- video/agon_ps2.h
- video/context.h
- video/context/fonts.h
- video/context/graphics.h
- video/hexload.h
- video/types.h
- video/vdu_buffered.h
- video/vdu_sys.h
- video/video.ino
Once again, merged in forgetting to squash :(
> Re-re-creation of PR 256

- video/agon.h
- video/vdu_layers.h
- video/vdu_sys.h
`VDU 23,0,&C2,n` now checks whether the “tile engine” feature flag has been set before processing the command
this will allow us to release the tile engine whilst the API is still in a state of potential flux
> add feature flag 0x300 for tile engine

- video/agon.h
- video/feature_flags.h
- video/vdu.h
- video/vdu_buffered.h
- video/vdu_stream_processor.h
- video/vdu_sys.h
Enhances "conditional" buffered commands to allow conditions to use a feature flag as the source value being checked against.  This is done by setting the bit `0x40` on the condition operation, and providing a `featureFlagId` instead of the `checkBufferId`.  When this flag is set a `checkOffset` must not be sent - it is meaningless when reading a flag.
Conditional checks now also support checking against 16-bit values, whether the source value is from a buffer, or from a feature flag, via setting the bit `0x80` on the condition operation.
A new buffered command has been added to allow for the value of a feature flag to be read and copied into a buffer at a given offset.  The format of this command is:
`VDU 23, 0, &A0, <bufferId>; &30, <options>, <offset>; <flagId>; [default[;]]`
The …
> Allow use of feature flags in buffered commands

- platformio.ini
- video/agon.h
- video/agon_screen.h
- video/buffers.h
- video/vdu.h
- video/vdu_buffered.h
- video/vdu_stream_processor.h
- video/vdu_sys.h
- video/video.ino
This PR adds "copper" style features to the VDP.  What this means is the ability to dynamically change the palette in palette-based screen modes during scan-out.  This enables the ability for screen modes with 2, 4 or 16 colours to potentially display all 64 colours on screen at once.
This adds a “copper” feature flag (`&310`), and VDU commands to use this new feature
VDU commands begin with `VDU 23,0,&C4,<command>`
The command set allows a palette, with a 16-bit ID, to be added, deleted, and for colours within that palette to be defined using RGB888 values (similar to normal palette changes).  Also the output “signal list” can be updated, which allows different palettes to be used on different rows during scan-out.  The command to update the signal list accepts a buffer which must …
> Add preliminary “copper” functions

- video/agon.h
- video/agon_ps2.h
- video/agon_screen.h
- video/context.h
- video/context/cursor.h
- video/context/graphics.h
- video/context/viewport.h
- video/feature_flags.h
- video/vdu.h
- video/vdu_stream_processor.h
- video/vdu_sys.h
- video/video.ino
Context state as “VDU Variables” within the feature flag space
These variables occupy the range 0x1000-0x1FFF
Where appropriate, variables can be written to, adjusting the underlying graphics system state.
Some additional variables related to system state, and thus not strictly "vdu variables" are also added inside the range 0-0xFFF
The first set of variables implemented closely matches VDU Variables (including Mode Variables) on RISC OS systems.  Additional variables that are Agon-specific, or exposing the graphics system state that RISC OS does not provide access to via their VDU Variables mechanism (but may be available elsewhere) have also been added.
(Builds on #285)
> Expose graphics context state as “VDU Variables”

- video/context/graphics.h
this fixes an issue whereby performing a CLS can leave behind a “cursor block”, fixing #284
> temporarily hide/show cursor on CLS

- video/sprites.h
`addSpriteFrame` will now reject adding “Native” or “Undefined” format bitmaps to a sprite.  if a “Mask” (mono) format bitmap is added then a hardware sprite will be downgraded to software sprite, as we don’t support mask format bitmaps in hardware sprites
a call to `setSpritePaintMode` using any mode other than 0 (set) will force the sprite to be a software sprite
> auto-degrade hardware sprites

- video/audio_channel.h
ensure that the `AudioChannel::setParameter` function doesn’t cause a double mutex lock
ensure that `setFrequency` and `setVolume` update the frequency/volume when no corresponding envelope is set
> audio fixes

- video/agon.h
- video/vdu_context.h
adds a call to select context 0 into `resetAllContexts`, ensuring that the default is set, and also ensure that the stack is saved
also add a context debug call to see info about available contexts
> ensure mode change selects default context

- video/sprites.h
- video/vdu_sprites.h
adds a pair of new commands to the sprite API that will let you replace the currently selected frame of a sprite with a different bitmap
> replace current sprite frame command

- video/agon_screen.h
These modes are supported by vdp-gl and allow users that have 1280x1024 monitors to display in its native 5:4 ratio, instead of a stretched 4:3 when using 640x480.
> Add new 640x512 and 640x256 screen modes.

- platformio.ini
- video/updater.h
updates vdp-gl to the new `firm-sprites` tag which includes fixes for a crash triggered when the firmware update process is happening, and a crash that can occur when using hardware sprites with RGBA2222 format bitmaps
also includes some very minor tweaks to the firmware updater code
> fix firmware update, and hardware sprites

- README.md
- platformio.ini
- video/agon.h
- video/agon_ps2.h
- video/context.h
- video/context/cursor.h
- video/vdp_protocol.h
- video/vdu.h
- video/vdu_stream_processor.h
- video/vdu_sys.h
- video/video.ino
paged mode now works more like Acorn machines
page size in paged mode now ensures that 6 lines of “context” remain from the previous page, if available.  this means that if the cursor was at the top of the screen the page fills to the bottom, but if the cursor is at the bottom of the screen the 6 rows above the cursor when printing begins will be kept
the count of rows to be shown is reset when the cursor flashes, which means that paged mode only actually kicks in when a block of text is being printed
holding down `ctrl` will introduce a small delay when printing a new-line character
holding ctrl+shift pauses output at a newline
VSYNC callbacks will now get called when paged mode is pausing MOS-originated VDU commands
VDP Variables have been added that provide control over this behaviour, …
> enhanced paged mode

- video/version.h
- video/video.ino
the `VERSION_VARIANT` is now “Platform” to be in-line with the new MOS 3.0 release, and to reflect our organisation name change
support for a `VERSION_SUBTITLE` added, which for this release is “Dressing Gown”, after all, can one imagine Arthur without his dressing gown?
> bump version to 2.14.0

- video/vdu_fonts.h
- video/vdu_sys.h
before VDP 2.14.0, the boot up sequence would _always_ send mode info to MOS after `wait_eZ80` was completed.
the call to `sendModeInformation`  into the `wait_eZ80` function was moved inside `wait_eZ80`, however how this was done meant that that a software reset of the ESP32, caused by a VDP flash when MOS will still be running, did _not_ send mode information across
as the agon-flash tool was using the updated mode information as a signal that the VDP had rebooted it would then fail to recognise the VDP restart
this fixes the `wait_eZ80` behaviour, ensuring that mode info will always be sent
also adds some calls to `sendModeInformation` against a few font API functions that could, potentially, result in changed the mode info
> send mode info a bit more
