video/agon.h, video/agon_audio.h, video/envelopes.h, video/envelopes/frequency.h, video/envelopes/volume.h, video/vdu_audio.h, video/video.ino
Provides an enhanced audio system on the Agon Light platform.
Supports up to 32 channels, with configurable waveform type, PCM sample playback, plus volume and frequency envelopes.
=> Audio enhancements, including frequency envelope support

video/agon.h, video/agon_audio.h, video/agon_fonts.h, video/agon_keyboard.h, video/agon_screen.h, video/cursor.h, video/envelopes/frequency.h, video/envelopes/volume.h, video/graphics.h, video/sprites.h, video/vdp_protocol.h, video/vdu.h, video/vdu_audio.h, video/vdu_sprites.h, video/vdu_sys.h, video/video.ino, video/viewport.h
Big refactor of the codebase, splitting into different concerns
With this PR, the code remains _mostly_ identical to upstream VDP, but functions and data declarations have been moved into separate files.  Some refactoring has been done to split out functionality into separate functions to provide a cleaner separation.
In general, files named with a prefix of `agon_` are responsible for hardware features, those starting with `vdu` are handlers of the VDU byte streams.  Other files provide higher level capabilities/abstractions.
Addresses #10
=> Refactor codebase

video/agon.h, video/agon_audio.h, video/agon_keyboard.h, video/audio_channel.h, video/audio_sample.h, video/cursor.h, video/enhanced_samples_generator.h, video/graphics.h, video/vdp_protocol.h, video/vdu.h, video/vdu_audio.h, video/vdu_sprites.h, video/vdu_stream_processor.h, video/vdu_sys.h, video/video.ino
Implements #24
Introduces a VDUStreamProcessor class, which is responsible for VDU command handling.
On startup a stream processor gets created, passing in the z80 comms stream.
In the main loop, `processor->processAllAvailable()` gets called, processing all available VDU commands from the comms stream.
Most of the code remains the same, beyond being moved around a bit.  There is some minor refactoring to the audio code along with the re-arrangement to make slightly better (more appropriate) use of C++ smart pointers.
This is the "hard work" part that should allow us to implement #8 and #3 relatively easily now that this has been done
=> Refactor VDU command handling

video/agon.h, video/vdu_buffered.h, video/vdu_stream_processor.h
Adds commands to allow for buffer contents to be programatically changed (adjust), as well as to allow conditions to be checked to decide whether to call a buffer.
Documentation and examples will come soon
=> Support for adjusting buffers, and conditionally calling them

video/agon.h, video/multi_buffer_stream.h, video/vdu_buffered.h, video/vdu_stream_processor.h
renumber adjust commands
also contains a "call" fix to ensure that loops work better
=> Buffered command tweaks

video/graphics.h
Fixes breakintoprogram/agon-vdp#129
=> fix: plot point should move the graphics cursor

video/graphics.h, video/sprites.h, video/vdu.h, video/vdu_sys.h
plus slightly optimise our use of the graphics plot operation queue for a small graphics performance improvement
=> update graphics cursor correctly

README.md, platformio.ini, video/agon_ps2.h
also add support for the new keyboard layouts it includes with thanks to @lennart-benschop for the original PR to add those layouts
=> update to new vdp-gl

video/vdu_sprites.h
create monochrome bitmaps using graphics foreground colour
also fixes logic for working out width in bytes of monochrome bitmaps.  bitmaps are assumed to have a complete number of bytes per row, and start at the top-most bit.  the width given is a pixel width, and does not have to be a multiple of 8.  the final byte in a row will have pixels ignored if the width is not a multiple of 8.
=> fix mono bitmaps

README.md, platformio.ini, video/agon_ps2.h
Reverts AgonConsole8/agon-vdp#93
=> Revert "update to new vdp-gl"

video/agon.h, video/agon_audio.h, video/audio_channel.h, video/audio_sample.h, video/enhanced_samples_generator.h, video/envelopes/frequency.h, video/envelopes/volume.h, video/vdu.h, video/vdu_audio.h, video/vdu_stream_processor.h, video/video.ino
Based on work by @MovieVertigo in breakintoprogram/agon-vdp#143
extending to do some tidying up of audio system, and enhancing with a few new features
todo:
=> Allow frequency changes on audio samples

video/agon_ps2.h
functionally the same as #100 but matching code style and resolving conflicts
=> add br-pt and dvorak keyboard layouts

video/agon.h, video/graphics.h, video/sprites.h, video/vdu_sys.h
=> allow character to be mapped to a bitmap

video/video.ino
=> Init video early, so your LCD can start syncing while other VDP setup happens

video/video.ino
fixes an issue whereby the mouse positioner would not work properly until after a mode change
=> fix mouse positioner on reboot

video/vdu_sys.h
=> send palette index for text/graphics colours

video/vdu_sys.h
=> flush drawing queue on font changes

video/graphics.h
Addresses the character matching part of #169
=> Allow get screen character to match chars 0-31

platformio.ini, video/graphics.h, video/vdu.h
relies on updated vdp-gl for this functionality
=> add support for arc, segment and sector plot codes

video/vdu_stream_processor.h
changes peekByte_t to match the style of readByte_t
=> change peekByte_t implementation to match

video/agon_ttxt.h, video/graphics.h
Made scrollRegion in graphics.h take teletext mode scrolls in all four directions.
Added x and y parameters to agon_ttxt:scroll method and implement these directions in the scroll method. Everything other than scrolling the whole screen up is slow as it repaints the entire screen.
Tested with VDUU23,16 calls for all four scrolling directions in MODE 7.
=> Added MODE7 scroll in all four directions

video/context.h, video/context/graphics.h, video/vdu.h, video/vdu_stream_processor.h
stage 1 in optimising string plotting
strings are read from the VDU stream, and processed into drawing commands to be processed in one block
super-rough timing shows a long program listing that took approximately 15s to complete now takes 10s
=> optimised string printing

video/agon.h, video/compression.h, video/vdu_buffered.h, video/vdu_stream_processor.h
Rebase on current (new) main branch, plus some small tidying up of the buffer compression/decompression functionality from @TurboVega in #185, renumbering of buffered commands, and some adjustment of comments to match functionality
(git commit history tidied up a bit)
=> Compression and decompression

platformio.ini, video/agon.h, video/agon_audio.h, video/audio_channel.h, video/context.h, video/context/graphics.h, video/vdu.h, video/vdu_audio.h, video/vdu_buffered.h, video/video.ino
Experiment to run main loop on core 0
(builds on #209 )
=> Experimental main loop

video/agon_audio.h, video/audio_channel.h
This fixes race conditions in the audio subsystem, and simplifies its operation
=> Audio subsystem rework

video/agon_screen.h, video/vdu_sys.h
and turn off queue timeout, restoring back to earlier performance when printing text
fix based off work by @jblang
=> fix printBuffer

video/context/cursor.h, video/context/viewport.h
=> fix text print when changing text viewport

video/agon_screen.h
adds screen modes 20-23 and 149-151 which provides 512x384 resolution in 64, 16, 4 and 2 colours (and double-buffered versions except for 64 colour
=> add 512x384 resolution screen modes

video/types.h, video/video.ino
Add terminal font change facility using sequence <ESC> + '_#Fnnnn$' when nnnn is the font number. Thanks Steve for the base code to start from!
=> Add terminal font change

video/vdu_layers.h, video/vdu_stream_processor.h, video/vdu_sys.h, video/video.ino
Pull request for initial release of the Tile Engine code for the Agon VDP.
=> Initial release of Tile Engine

video/vdu_context.h, video/vdu_stream_processor.h
implements idea to set a default context flag from #281
=> track context ID, and make default context ID 0

video/sprites.h, video/vdu_sprites.h
This adds commands to set or clear the hardware flag for the currently selected sprite.
=> support sprite hardware flag

video/context.h
fix mouse variables so that read and write match
split out cursor appearance bits into a separate value (write-only)
=> vdu variable fixes

video/vdu_buffered.h
=> fix degree to radian conversions
